libraryproject/urls.py
from django.contrib import admin
from django.urls import path,include
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', views.register,name='register'),
    path('adminregister/', views.admin_register,name='adminregister'),
]

main/urls.py
from django.urls import path,include
from . import views

app_name = 'main'
urlpatterns = [
    path('', views.homepage,name='home'),
    path('change/<int:id>', views.edit_book,name='change'),
    path('delete/<int:id>', views.delete,name='delete'),
    path('issue-book/<int:id>', views.issue_book,name='issuebook'),
    path('addbook', views.add_book,name='addbook'),
    path('booksissued', views.books_issued,name='booksissued'),
    path('all-books-issued', views.display_all_issued_books,name='all_books_issued'),
    path('returnbook/<int:id>', views.returnbook,name='returnbook'),
]

main/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
# Create your models here.
class Book(models.Model):
    '''Store information about a book'''
    
    name = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    availability = models.IntegerField()
    def __str__(self):
        return self.name

class LibraryAdmin(models.Model):
    '''Extending CustomUser model to perform CRUD operations on Book model'''

    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

class Student(models.Model):
    ''' Extending CustomUser model. This model is be used to add relation with Book model and store information regarding books issued by student. '''

    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    books_issued = models.ManyToManyField(Book,through="Record")

    def __str__(self):
        return self.user.email

class Record(models.Model):
    '''Intermediate model to store info about transaction that takes place when student issues a book'''

    student = models.ForeignKey(Student,on_delete=models.CASCADE)
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    date_issued = models.DateField(default=timezone.now)

main/views.py
from django.shortcuts import redirect, render,HttpResponseRedirect
from django.urls import reverse
from .models import Book,Record
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.
def homepage(request):
    '''Display all the books'''

    books = Book.objects.all()
    return render(request,'main/home.html',{'books':books})

@login_required
def edit_book(request,id):
    ''' only admin has access to edit books. Select the book object by id passed through URL and change its attributes '''

    if request.user.is_superuser:
        book = Book.objects.get(pk=id)
        if request.method == 'POST':
            bname = request.POST.get('bookname')
            category = request.POST.get('category')
            num = request.POST.get('num')
            book.name = bname
            book.category = category
            book.availability = num
            book.save()
            messages.success(request,'Book Edited successfully')

            return HttpResponseRedirect(reverse('main:home'))

        return render(request,'main/editBook.html',{'book':book})
    else:
        messages.error(request,'Your account doesn\'t have access to this page.')
        return redirect(reverse('main:home'))

@login_required
def add_book(request):
    '''Only the admin has access to add books. Perform checks on data provided and if also book already exists provide a link to edit book    '''

    if request.user.is_superuser:
        if request.method=='POST':
            bname = request.POST.get('bookname')
            category = request.POST.get('category')
            num = request.POST.get('num')
            bookobj = Book.objects.filter(name=bname,category=category)
            if bookobj:
                messages.info(request,'book already exists')
                return render(request,'main/addBook.html',{'book':bookobj[0]})
            elif len(bname) <2:
                messages.error(request,'book name too short')
            elif len(category) <2:
                messages.error(request,'category too short')
            else:
                Book.objects.create(name=bname,category=category,availability=num)
                messages.success(request,'Book Added!')
                return HttpResponseRedirect(reverse('main:home'))
        return render(request,'main/addBook.html')
    else:
        messages.error(request,'Your account doesn\'t have access to this page.')
        return redirect(reverse('main:home'))

@login_required
def delete(request,id):
    '''only admin has access to delete books. Select the book object by id passed through URL and delete the object'''
    
    if request.user.is_superuser:
        book = Book.objects.get(pk=id)
        book.delete()
        messages.error(request, 'Book deleted')
    else:
        messages.error(request,'Your account doesn\'t have access to this page.')
    return redirect(reverse('main:home'))

@login_required
def issue_book(request,id):
    '''Select the student through request object, Select the book object by id passed through URL. Check if student has already issued this book, availability of the book, and enforce student can only issued 3 books. Add the book to Student m2m relation with the Book'''

    student = request.user.student
    book = Book.objects.get(pk=id)
    if book in student.books_issued.all():
        messages.error(request,'you already have issued this book')
        return redirect(reverse('main:booksissued'))
    elif book.availability <1:
        messages.error(request,'No books available')
        return redirect(reverse('main:home'))

    elif not (student.books_issued.all().count() <3):
        messages.error(request,'you already have issued 3 books return a book to issue a new one')
        return redirect(reverse('main:booksissued'))
    else:
        student.books_issued.add(book)
        book.availability -= 1
        book.save()
        return HttpResponseRedirect(reverse('main:booksissued'))

@login_required
def display_all_issued_books(request):
    '''only admin has access to view all issued books.'''
    if request.user.is_superuser:
        records = Record.objects.all()
        return render(request,'main/allIssuedBooks.html',{'records':records})
    else:
        messages.error(request,'Your account doesn\'t have access to this page.')
        return redirect(reverse('main:home'))

@login_required
def returnbook(request,id):
    '''Select the student through request object, Select the book object by id passed through URL.Remove the book from Student m2m relation with the Book'''
    student = request.user.student
    book = Book.objects.get(pk=id)
    if book in student.books_issued.all():
        student.books_issued.remove(book)
        book.availability +=1
        book.save()
        return HttpResponseRedirect(reverse('main:home'))
    else:
        messages.error(request,'you have not issued this book')
        return HttpResponseRedirect(reverse('main:home'))

@login_required
def books_issued(request):
    ''' list all books issued by a student'''
    student = request.user.student
    records = student.record_set.all()
    return render(request,'main/books.html',{'records':records})

main/templates/main/addBook.html
{% extends 'main/base.html' %}
{% block content %}


<div class="container">
  <form method="POST">
  {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Book Name</label>
      <input type="text" name = "bookname"  class="form-control" id="exampleInputEmail1" >
      
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Category</label>
      <input type="text" name="category" class="form-control"  id="exampleInputPassword1">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Number of books available</label>
      <input type="text" class="form-control" name="num"  id="exampleInputPasswor">
    </div>
   
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  </div>
{% endblock content %}

main/templates/main/allIssuedBooks.html
{%extends 'main/base.html'%}
{% block title %}all books issued{% endblock title %}
{% block content%}
   <div id="table" class="my-3">
         <h2>All issued books</h2>
        <table class="table table-dark table-striped">
            <thead>
              <tr>
                
                <th scope="col">Student</th>
                <th scope="col">Book Name</th>
                <th scope="col">Issued on</th>
              </tr>
            </thead>
            <tbody id="tableBody">
              {% for record in records %}
                <tr>
                    <td>{{record.student}}</td>
                    <td>{{record.book}}</td>
                    <td>{{record.date_issued}}</td>
                    
                </tr>
              {% endfor %}
            </tbody>
          </table>
      </div>
{% endblock%}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title> {% block title %}Home
    {% endblock title %} </title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">{% if user.is_authenticated%}{{user}}{%else%}Guest{%endif%}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
     <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      class="nav-item" >
      <li>
          <a class="nav-link"   href="{% url 'main:home'%}">Home</a>
        </li>
      {% if user.is_authenticated%}
      {% if user.student%}
        <li class="nav-item" >
          <a class="nav-link"   href="/booksissued">Books Issued</a>
        </li>
        {%endif%}
        <li class="nav-item" >
          <a class="nav-link"   href="/accounts/logout">logout</a>
        </li>
          {% if user.is_superuser%}
        <li class="nav-item" >
          <a class="nav-link"   href="{% url 'main:addbook'%}">Add Book</a>
        </li>
        <li class="nav-item" >
          <a class="nav-link"   href="{% url 'main:all_books_issued'%}">All Issued Books</a>
        </li>
          {%endif%}
        {%else%}
        <li class="nav-item" >
          <a class="nav-link"   href="/accounts/login">Login</a>
        </li>
        <li class="nav-item" >
          <a class="nav-link"   href="/register">Signup</a>
        </li>
        {%endif%}
      </ul>
    </div>
  </div>
</nav>

{% if messages%} 
        {% for message in messages%}
        {% if message.tags == 'success'%}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
         {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% elif message.tags == 'info'%}
        <div class="alert alert-info" role="alert">
         {{message}} <a href="{% url 'main:change' book.id%}" class="alert-link">Edit the book</a>
      </div>
        {%else%}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
         {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endif%}
        {% endfor %}
      {%endif%}
    
    {% block content %}{% endblock content %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

main/templates/main/base3.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>{% block title %}Home{% endblock title %}</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:home'%}">HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
      {% if user.is_authenticated%}
      {% if user.student%}
        <li class="nav-item" >
          <a class="nav-link"   href="/booksissued">Books Issued</a>
        </li>
        {%endif%}
        <li class="nav-item" >
          <a class="nav-link"   href="/accounts/logout">logout</a>
        </li>
          {% if user.is_superuser%}
        <li class="nav-item" >
          <a class="nav-link"   href="{% url 'main:addbook'%}">Add Book</a>
        </li>
          {%endif%}
        {%else%}
        <li class="nav-item" >
          <a class="nav-link"   href="/accounts/login">Login</a>
        </li>
        <li class="nav-item" >
          <a class="nav-link"   href="/register">Signup</a>
        </li>
        {%endif%}
      </ul>
    </div>
  </div>
</nav>

    {% if messages%} 
        {% for message in messages%}
        {% if message.tags == 'success'%}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
         {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% elif message.tags == 'info'%}
        <div class="alert alert-info" role="alert">
         {{message}} <a href="{% url 'main:change' book.id%}" class="alert-link">Edit the book</a>
      </div>
        {%else%}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
         {{message}}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {%endif%}
        {% endfor %}
      {%endif%}
    
    {% block content %}{% endblock content %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

main/templates/main/books.html
{% extends 'main/base.html'%}
{% block title %}books issued{% endblock title %}
{% block content%}
   <div id="table">
          <h1>Your Books</h1>
        <table class="table table-dark table-striped">
            <thead>
              <tr>
                
                <th scope="col">Book Name</th>
                <th scope="col">Issued on</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody id="tableBody">
              {% for record in records %}
                <tr>
                    <td>{{record.book.name}}</td>
                    <td>{{record.date_issued}}</td>
                    <td><a href="{% url 'main:returnbook' record.book.id %}"><button class="btn btn-primary btn-sm">Return Book</button></a>
                    </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
      </div>
{% endblock%}

main/templates/main/editBook.html
{% extends 'main/base.html' %}
{% block content %}


<div class="container">
  <form method="POST">
  {% csrf_token %}
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Book Name</label>
      <input type="text" name = "bookname" value="{{book.name}}" class="form-control" id="exampleInputEmail1" >
      
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Category</label>
      <input type="text" name="category" class="form-control" value="{{book.category}}" id="exampleInputPassword1">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Number of books available</label>
      <input type="text" class="form-control" name="num" value="{{book.availability}}" id="exampleInputPasswor">
    </div>
   
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  </div>
{% endblock content %}

main/templates/main/home.html
{% extends 'main/base.html'%}

{% block content%}
   <div class="my-3" id="table">
          <h1>Library Books</h1>
        <table class="table table-dark table-striped">
            <thead>
              <tr>
                
                <th scope="col">Name</th>
                <th scope="col">Category</th>
                <th scope="col">Availability</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody id="tableBody">
              {% for book in books %}
                <tr>
                    <td>{{book.name}}</td>
                    <td>{{book.category}}</td>
                    <td>{{book.availability}}</td>
                    <td>
                    {% if user.is_superuser%}
                    <a href="{% url 'main:change' book.id %}"><button class="btn btn-primary btn-sm">Edit Book</button></a>
                    <a href = "{% url 'main:delete' book.id %}"><button class="btn btn-primary btn-sm mx-3">Delete Book</button></a>
                    {%else%}
                    <a href = "{% url 'main:issuebook' book.id %}"><button class="btn btn-primary btn-sm mx-3">Issue Book</button></a>
                    {%endif%}
                    </td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
      </div>
{% endblock%}